### ISSUE TITLE
ashape3d function

### ISSUE THREAD

**Issue by stefanoch90** [tlafarge/alphashape3d#10]
Hi, i congratulate you for your package.
I have a question, i don't upload my matrix array into "ashape3d" function , but the system says me "non-numeric argument to binary operator".
How can i solve this problem?
Thank you very much.

**Comment by tlafarge** [comment]
Ideally  your matrix array should be passed as a 3 columns matrix to the ashape3d function like here:
data_array= matrix( runif(300), nc=3)

plot( ashape3d( data_array, alpha = 0.4))
