### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tcristea** [tlafarge/alphashape3d#6]
_I've encountered this behaviour on a 3 dimensional data set, with duplicates removed:_

**\* caught segfault ***
address 0xc0b17c28, cause 'memory not mapped'

Traceback:
 1: .C("int1", dup1, as.integer(nvt), as.integer(ned), in.edo, auxmu2,     Mu2, mu1, mu1up, PACKAGE = "alphashape3d")
 2: ashape3d(as.matrix(intabl), alpha = 0.1)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

_The output of R.Version() is_ 

$platform
[1] "x86_64-pc-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "3.0"

$year
[1] "2016"

$month
[1] "05"

$day
[1] "03"

$`svn rev`
[1] "70573"

$language
[1] "R"

$version.string
[1] "R version 3.3.0 (2016-05-03)"

$nickname
[1] "Supposedly Educational"

> packageVersion("alphashape3d")
> [1] ‘1.2’

_In the attached zip there is a single rds archive with a list of data frames; the call to ashape3d gives segmentation fault for the list's elements with indices 2, 6, 8, 11, 12, 16 out of a total of 19. I've split a larger data set in the list after removing the duplicates to eliminate the possibility of encountering the same problem as in an already closed issue and in order to narrow the problem.  I've verified that the problem stays when installing fresh from github._

[listIntabLongCPP.zip](https://github.com/tlafarge/alphashape3d/files/310843/listIntabLongCPP.zip)

**Comment by tcristea** [comment]
I've had the clue from the beginning that the issue has to do with the precondition that the data points ought to be in general position, but I thought that calling ashape3d function with "pert = TRUE" would be sufficient (it isn't as per this issue).
I think the solution is as follows:
Set << options = "QJ" >> in the call to delaunayn function (line number 45, in the file ashape3d.R, then rebuild and redeploy the package.

**Comment by tlafarge** [comment]
Sorry for not getting back to you earlier,
Thanks for the find we are in the process offixing it and uploading to CRAN (the github is just a mirror.
Will fix with  
        tc <- matrix(delaunayn(x), ncol = 4)

to
            tc <- matrix(suppressMessages(delaunayn(x,options = "QJ")), ncol = 4)
