### ISSUE TITLE
Calculating shape surface area

### ISSUE THREAD

**Issue by harryjfowen** [tlafarge/alphashape3d#8]
Hi there,

I was wondering whether it is possible to compute the surface area of the alpha shape object? 

Thanks!

Harry

**Comment by beatrizpateiro** [comment]
Hi Harry,
The function surfaceNormals computes the normal vectors of all the
triangles which belong to the boundary of the α-shape. The magnitude of
each vector is equal to the area of its associated triangle. Therefore you
can do:

x <- matrix(runif(20000), nc = 3)
ashape3d.obj <- ashape3d(x, alpha = 10)
sn<-surfaceNormals(ashape3d.obj, display = TRUE)
sum(sqrt(rowSums(sn$normals^2)))  #Surface area of the alpha shape

Best,
Bea

**Comment by harryjfowen** [comment]
Perfect! thanks for your quick response. 

Best

Harry
